version: '3.9'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: bash -c "npm install && npm run build && npm run start"
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=production